### ISSUE TITLE
Need help with extension

### ISSUE THREAD

**Issue by Dom-in** [Strencher/vsc-BBD-autocomplete#1]
Hello i was looking how to use this i cant find any way to use that extension

**Comment by RazerMoon** [comment]
Look up BBD-Autocomplete in the Extension tab of VSCode or go to [this link.](https://marketplace.visualstudio.com/items?itemName=Strencher.BetterDiscord-Autocomplete)

Gif of where the install button will be:

![w](https://user-images.githubusercontent.com/33849459/80827435-dcfeb480-8bdb-11ea-806a-587249e89d57.gif)

**Comment by Strencher** [comment]
^
